name: ev_guardian
description: Smart EV Battery Intelligence App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.15
  provider: ^6.1.1
  permission_handler: ^11.3.0
  lottie: ^2.3.1   # â† Added Lottie package


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
